name: Deploy

on:
  release:
    types: [released]
    paths: ["**.go", go.mod, go.sum, .github/workflows/deploy.yml]

  workflow_call:
    secrets:
      GCP_CREDENTIALS:
        description: "Service Account Key JSON"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE: gcr.io/${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ./bin/app

      - name: GCP Auth
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          token_format: "access_token"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@v3
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.gcp-auth.outputs.access_token }}"
          registry: "gcr.io"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags:
            - ${{ env.IMAGE }}:latest
            - ${{ env.IMAGE }}:${{ github.sha }}
          cache-to: type=inline
          cache-from: type=registry,ref=${{ env.IMAGE }}:latest

      - id: cloud-run
        name: Deploy Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ github.event.repository.name }}
          image: ${{ env.IMAGE }}

      - name: Deploy URL
        run: echo ${{ steps.cloud-run.outputs.url }}
