name: Release
on:
  push:
    branches: [master, qa]
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - .github/workflows/release.yml
      - containers/deploy.dockerfile

jobs:
  tests:
    permissions:
      contents: read
      pull-requests: read
      checks: write
    uses: ./.github/workflows/tests.yml

  deploy-qa:
    needs: [build]
    if: ${{ github.ref == 'refs/heads/qa' }}
    name: Deploy QA
    uses: ./.github/workflows/deploy.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_QA }}

  deploy-prod:
    needs: [build]
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Deploy Prod
    uses: ./.github/workflows/deploy.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_PROD }}

  release:
    needs: [deploy-prod]
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tag
        id: tag
        uses: anothrNick/github-tag-action@1

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          body_path: release.md
