name: Release
on:
  push:
    branches: [master, qa]
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - dockerfile
      - .github/workflows/release.yml
      - .github/workflows/deploy.yml
      - .github/workflows/tests.yml

jobs:
  deploy-qa:
    if: ${{ always() && github.ref == 'refs/heads/qa' }}
    name: Deploy QA
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: read
      pull-requests: read
      checks: write
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_QA }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    with:
      REQUIRED_TESTS: ${{ vars.REQUIRED_TESTS_PROD || false }}

  release:
    if: ${{ always() && github.ref == 'refs/heads/master' }}
    name: Release
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tag
        id: tag
        uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          body_path: release.md

  deploy-prod:
    needs: [release]
    name: Deploy Prod
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: read
      pull-requests: read
      checks: write
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_PROD }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    with:
      TAG: ${{ needs.release.outputs.tag }}
      REQUIRED_TESTS: ${{ vars.REQUIRED_TESTS_PROD || true }}
