name: Tests
on:
  workflow_call:
  push:
    branches-ignore: [master, qa]
    paths: ["**.go", go.mod, go.sum, .github/workflows/tests.yml]

jobs:
  cache:
    name: Cache Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

  static_tests:
    name: Static Tests
    needs: [cache]
    permissions:
      contents: read
      pull-requests: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v4
        with:
          skip-cache: false
          skip-pkg-cache: false
          skip-build-cache: false

  unit_tests:
    name: Unit Tests
    needs: [cache]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Test
        uses: robherley/go-test-action@v0.2.0
